language: php

php:
 - "5.3"
 - "5.4"

before_install:
# Set the GitHub OAuth token to make use of the 6000 per hour rate limit
 - mkdir -p ~/.composer
 - cp .travis.composer.json ~/.composer/config.json
# Update composer
 - composer self-update
# Install project
 - composer install --prefer-dist --dev

before_script:
 - cd tests
 
script:
 - phpunit -d max_execution_time=0
 
after_script:
 - php vendor/bin/coveralls -v
